stages:
  - deploy
  - test


# templates
.install-deps:
  before_script:
    - pip install poetry
    - pip install nox nox-poetry
    - poetry --version
    - poetry config virtualenvs.in-project true
    - poetry install -vv
    - export ASTRODASK_TESTDATA_PATH=/testdata
    - export ASTRODASK_TESTDATA_SKIP="Illustris-3_snapshot"



# stages
## deploy/doc
pages:
  stage: deploy
  image: python:3.9
  extends: .install-deps
  script:
  - poetry run python -m ipykernel install --name astrodask
  - poetry run mkdocs build
  - mv ./site ./public
  allow_failure: true
  artifacts:
    paths:
    - public
  only:
  - main

## test
run_tests:
  tags:
    - datasets
  stage: test
  image: python:3.9
  extends: .install-deps
  script:
    - echo "testdata directory ($ASTRODASK_TESTDATA_PATH) content:"
    - ls $ASTRODASK_TESTDATA_PATH # test whether testdata mounted
    - echo "testdata to be skipped:"
    - echo $ASTRODASK_TESTDATA_SKIP
    - nox --python=3.9
    - nox --session=coverage --python=3.9
    - poetry run coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
