site_name: astrodask
repo_url: https://gitlab.mpcdf.mpg.de/byrohlc/astrodask
theme:
  name: material
  features:
    - content.code.annotate
    - navigation.sections

nav:
  - 'Readme': 'index.md'
  - 'Tutorial': tutorial.md
    #    - 'Getting Started': notebooks/gettingstarted.ipynb
    #    - 'Processing Large Data Sets': notebooks/static/largedatasets.ipynb
    #    - 'Series': notebooks/series.ipynb
    #    - 'Interactive Visualization': notebooks/static/visualization.ipynb
  - 'Misc':
    - 'Derived Fields': derived_fields.md
    - 'Supported Datasets': supported_data.md
    - 'Halo and galaxy catalogs': halocatalogs.md
  - 'Cookbook':
    - 'Units': notebooks/cookbook/units.ipynb
  - 'FAQ': faq.md
  - api_docs.md

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search:
  - mkdocs-video:
      css_style:
        float: left
        vertical-align: top
        height: 12.172vw
        width: 12.172vw
  - mkdocs-jupyter:
      execute: !ENV [JUPYTER_EXECUTE, true]
      execute_ignore: "notebooks/static/*.ipynb"  # waiting for list support (https://github.com/danielfrg/mkdocs-jupyter/issues/119)
      kernel_name: astrodask
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_signature_annotations: true
            show_source: true
            show_submodules: true
watch:
  - src/astrodask
