site_name: astrodask
repo_url: https://gitlab.mpcdf.mpg.de/byrohlc/astrodask
theme:
  name: material

nav:
  - Readme: 'index.md'
  - 'Tutorial': tutorial.md
    #    - 'Getting Started': notebooks/gettingstarted.ipynb
    #    - 'Processing Large Data Sets': notebooks/static/largedatasets.ipynb
    #    - 'Series': notebooks/series.ipynb
    #    - 'Interactive Visualization': notebooks/static/visualization.ipynb
  - 'Cookbook':
    - 'Units': notebooks/cookbook/units.ipynb
  - api_docs.md

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc

plugins:
  - search:
  - mkdocs-video:
      css_style:
        float: left
        vertical-align: top
        height: 12.172vw
        width: 12.172vw
  - mkdocs-jupyter:
      execute: !ENV [JUPYTER_EXECUTE, true]
      execute_ignore: "notebooks/static/*.ipynb"  # waiting for list support (https://github.com/danielfrg/mkdocs-jupyter/issues/119)
      kernel_name: astrodask
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_signature_annotations: true
            show_source: true
            show_submodules: true
watch:
  - src/astrodask
