[tool.poetry]
name = "astrodask"
version = "0.1.0"
description = "Convenience wrapper around astrophysical datasets to process with dask."
authors = ["Chris Byrohl"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.18"
dask = {extras = ["array", "dataframe", "distributed"], version = "^2022.12.1"}
distributed = "^2022.07"
h5py = "^3.7.0"
zarr = "^v2.10.0"
astropy = "^5.0"
numba = "^0.56"
pyyaml = ">=5.3.1"
jupyter = "^1.0.0"


[tool.poetry.dev-dependencies]
black = ">=22.1.0"
pre-commit = ">=2.17.0"
pytest = ">=6.2.5"
requests = ">=2.2.7"
coverage = "^7.0.1"

[tool.poetry.group.dev.dependencies]
pytest-xdist = {extras = ["psutil"], version = "^3.1.0"}
pytest-profiling = "^1.7.0"
mypy = ">=0.930"
mkdocs = "^1.3.0"
mkdocs-material = "^8.0.0"
mkdocstrings = {version = "^0.19.0", extras = ["python"]}
mkdocs-jupyter = "^0.22.0"
ipykernel = "^6.19.4"
matplotlib = "^3.6.2"
ipywidgets = "^8.0.4"

[tool.coverage.paths]
source = ["src", "*/site-packages"]
tests = ["tests", "*/tests"]

[tool.coverage.run]
branch = true
source = ["astrodask", "tests"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
