[tool.poetry]
name = "astrodask"
version = "0.1.0"
description = "Convenience wrapper around astrophysical datasets to process with dask."
authors = ["Chris Byrohl"]
readme = "README.md"

packages = [
    { include = "astrodask", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = ">=22.1.0"
pre-commit = ">=2.17.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
