# example for astrodask config. copy to ~/.astrodask.yaml and modify accordingly
---

copied_default: True  # if this is set, a warning is printed as the default config has not been adjusted
# adjust the config to your needs and remove above line to remove warning.
cache_path: ~/cachedir
testdata_path: /fastdata/public/testdata-astrodask  # should be replaced by 'datafolders' logic further below eventually
nthreads: 8

datafolders: ["/fastdata/public/testdata-astrodask", "/vera/ptmp/gc/byrohlc/astrodask-testdata", "/testdata",
              "/virgotng/universe/IllustrisTNG"]

missing_units: "warn"  # "warn", "raise", "ignore"

resources:
  mpcdf:
    TNG50:
      path: /virgotng/universe/IllustrisTNG/TNG50-1
    TNG100:
      path: /virgotng/universe/IllustrisTNG/TNG100-1
    TNG300:
      path: /virgotng/universe/IllustrisTNG/TNG300-1
  workstation:
    TNG50-4_snapshot:
      path: /data/public/testdata-astrodask/TNG50-4_snapshot
