# example for astrodask config. copy to ~/.astrodask.yaml and modify accordingly
---

copied_default: True  # if this is set, a warning is printed as the default config has not been adjusted
# adjust the config to your needs and remove above line to remove warning.
cache_path: ~/cachedir
testdata_path: /fastdata/public/testdata-astrodask  # should be replaced by 'datafolders' logic further below eventually
nthreads: 8

datafolders: ["/fastdata/public/testdata-astrodask", "/vera/ptmp/gc/byrohlc/astrodask-testdata"]

resources:
  mpcdf:
    TNG50:
      path: /virgotng/universe/IllustrisTNG/TNG50-1
    TNG100:
      path: /virgotng/universe/IllustrisTNG/TNG100-1
    TNG300:
      path: /virgotng/universe/IllustrisTNG/TNG300-1
  workstation:
    TNG50-4_snapshot:
      path: /data/public/testdata-astrodask/TNG50-4_snapshot

# some YAML aliases
defs:
  tng_params: &tng_params
    dataset_type: ArepoSimulation
    unitfile: units/illustris.yaml
  tng_props: &tng_props
    code: arepo
    suite: TNG
    tags: ["simulation"]
  illustris_params: &illustris_params
    dataset_type: ArepoSimulation

data:
  TNG50:
      <<: *tng_params
      aliases:
        - IllustrisTNG50
        - TNG50-1
      identifiers:
          Parameters:
            InitCondFile: /draco/ptmp/dnelson/InitialConditions/L35n2160TNG/output/ICs
  TNG50-2:
      <<: *tng_params
      identifiers:
          Parameters:
            InitCondFile: /draco/ptmp/dnelson/InitialConditions/L35n1080TNG/output/ICs
  TNG50-3:
      <<: *tng_params
      identifiers:
          Parameters:
            InitCondFile: /draco/ptmp/dnelson/InitialConditions/L35n540TNG/output/ICs
  TNG50-4:
      <<: *tng_params
      identifiers:
          Parameters:
            InitCondFile: /draco/ptmp/dnelson/InitialConditions/L35n270TNG/output/ICs
  TNG100:
      <<: *tng_params
      alias:
        - IllustrisTNG100
        - TNG100-1
      identifiers:
          Parameters:
            InitCondFile: /zhome/academic/HLRS/lha/zahapill/illustrisTNG_ics_201602/ics_illustrisTNGboxes/L75n1820TNG/output/ICs
  TNG300:
      <<: *tng_params
      alias:
        - IllustrisTNG300
        - TNG300-1
      identifiers:
          Parameters:
            InitCondFile: /zhome/academic/HLRS/lha/zahapill/illustrisTNG_ics_201602/ics_illustrisTNGboxes/L205n2500TNG/output/ICs

  # Illustris does not have config or header attributes for identification in hdf5 files
  Illustris:
      <<: *illustris_params
      aliases:
        - Illustris-1
        - Illustris100
  Illustris-2:
  Illustris-3:

  EAGLEtype:
    identifiers:
      Header:
        RunLabel: "\"Eagle"
    unitfile: units/eagle.yaml
