name: 'get-testdata'
description: 'download test data'
inputs:
  outputfolder:
    description: 'folder to download to'
    required: true
runs:
  using: 'composite'
  steps:
    - name: "Fetch 'minimal_FIRE2_snapshot_z1.hdf5'"
      run: |
         mkdir -p ${{ inputs.outputfolder }}
         cd ${{ inputs.outputfolder }}
         wget -O minimal_FIRE2_snapshot_z1.hdf5 https://heibox.uni-heidelberg.de/f/856c4ffbcc644530a27d/?dl=1
      shell: bash
