name: 'get-testdata'
description: 'download test data'
inputs:
  outputfolder:
    description: 'folder to download to'
    required: true
  url:
    description: 'url to download from'
    required: true
  filename:
    description: 'filename to save as'
    required: true
runs:
  using: 'composite'
  steps:
    - name: "Fetch '${{ inputs.filename }}'"
      run: ./.github/actions/get-testdata/download.sh ${{ inputs.outputfolder }}  ${{ inputs.filename }} ${{ inputs.url }}
      shell: bash
