name: 'setup poetry env'
description: 'setup the python/poetry environment'
{% raw %}
inputs:
  python-version:
    required: false
    description: 'python version'
    default: '3.9'
outputs: {}
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{inputs.python-version}}
    - name: Install poetry
      run: python -m pip install poetry
      shell: bash
    - name: Create virtual environment
      run: poetry install
      shell: bash{% endraw %}
